### ISSUE TITLE
wording for light-agents is misleading

### ISSUE THREAD

**Issue by YesThatAllen** [zendesklabs/ticket_redaction_app#44]
Light agents get a misleading error:

![screenshot_1677](https://cloud.githubusercontent.com/assets/2879972/16130732/1d77841e-33d0-11e6-8ed9-e3711fd69034.png)

`Unfortunately your role does not have access to redaction. Your administrator can change your role to allow 'ticket deletion' and enable this app.`

Would be far simpler/clearer/better to simply say

`Your role does not have access to redaction.`

would take less precious space in the sidebar too.

**Comment by aeverson** [comment]
Hi @YesThatAllen ,

I understand your point on sidebar real estate, but I wanted to clarify the point about roles. If you're a light agent, the error message tells you to contact your admin in order to change your role (to a role that allows ticket deletion) in order for the app to work. I get how that could be misinterpreted to mean "alter the properties of your role" though. We do like having that statement there, but we'll think about how to make that clearer.
