### ISSUE TITLE
Can't redact files from closed ticket

### ISSUE THREAD

**Issue by harlandlee** [zendesklabs/ticket_redaction_app#65]
Ticket is closed and I get the error: 'One or more of the redactions failed...please try again'
The attachment is a zip file.

**Comment by dpawluk** [comment]
Unfortunately you cannot edit closed tickets by design. The only way to remove the data would be to delete the ticket. This has to do with how Zendesk works, and not the app so there is nothing I can help with. I might suggest joining a discussion about editing closed tickets on the Zendesk product feedback forums. Thanks
