### ISSUE TITLE
Other users not able to use app.

### ISSUE THREAD

**Issue by FridtjofHals** [zendesklabs/ticket_redaction_app#72]
Hi.

I'm having some problems with user management within your app.
In the settings section I have not enabled any restrictions for usage, yet users get message 'Unfortunately your role does not have access to redaction. Your administrator can change your role to allow 'ticket deletion' and enable this app'.
But, if I enable the restriction, and then select a role and/or group, then the message does not change and user is still not able to use app.

Any suggestions?

**Comment by madlatino2008** [comment]
Hi there,

I am having the same issue. I have made it public to all users but only I am able to use the app since I installed it and no one else can use it. Even if I limit to agents only, they are not able to use it.

**Comment by itinkoff** [comment]
The same for me as well, the following error is shown
![capture](https://user-images.githubusercontent.com/22316791/38760663-1db7c81e-3fa7-11e8-8976-bc1dcef134a6.PNG)

**Comment by dpawluk** [comment]
Hi there. Unfortunately this won't be fixed in the current version of the app. A V2 version of the redaction app should be coming out in May however and any issues here should be rectified in that version of the app. Thank you for your patience. @madlatino2008 and @FridtjofHals This might be because the other agents do not have permission to 'delete a ticket'. If you adjust that setting for agents they should be able to redact as well.
